service: companion-bridge
provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/server.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000